---
abstract: 'Sniff info from your Google Wave Inbox'
author:
  - 'Joe Higton'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Wave-Sniff
no_index:
  directory:
    - inc
    - t
requires:
  JSON: 2.16
  LWP: 5.812
  Moose: 0.55
  Readonly: 1.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.1_002
